### PR TITLE
Adding next meeting

### PR DESCRIPTION
**Pull request by mfavetti**

### CODE REVIEW

**Comment by srkirkland** [comment]
@cthielen Sweet get @mfavetti a prize!  BTW is this setup to auto-deploy or do you want to merge and then start the update process?

**Comment by cthielen** [comment]
Hey, it's not set up to auto-deploy but I think it's time to switch it over to gh-pages.

What's the process on that? Just need to set the A record to GitHub.com's?

**Comment by cthielen** [comment]
My apologies on the delay on this. I didn't have the GitHub static hosting going until today. Please don't let this discourage you from PRing in the future. :)

**Comment by mfavetti** [comment]
No problem at all!

**Pull request merged**
